package org.openubl.models;

public enum FileDeliveryStatusType {
    SCHEDULED_TO_DELIVER,
    SCHEDULED_TO_DELIVER_FAILED,
    RESCHEDULED_TO_DELIVER,
    SCHEDULED_CHECK_TICKET,
    RESCHEDULED_CHECK_TICKET,
    ERROR_SCHEDULING_CHECK_TICKET,
    SCHEDULED_CALLBACK,
    ERROR_SCHEDULING_CALLBACK,
    OK
}
