/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.project.openubl.xsender.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DocumentKafka extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5520818640965253842L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentKafka\",\"namespace\":\"io.github.project.openubl.xsender.avro\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"retry\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DocumentKafka> ENCODER =
      new BinaryMessageEncoder<DocumentKafka>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentKafka> DECODER =
      new BinaryMessageDecoder<DocumentKafka>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DocumentKafka> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DocumentKafka> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DocumentKafka> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DocumentKafka>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DocumentKafka to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DocumentKafka from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DocumentKafka instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DocumentKafka fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String id;
   private int retry;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentKafka() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param retry The new value for retry
   */
  public DocumentKafka(java.lang.String id, java.lang.Integer retry) {
    this.id = id;
    this.retry = retry;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return retry;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: retry = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'retry' field.
   * @return The value of the 'retry' field.
   */
  public int getRetry() {
    return retry;
  }


  /**
   * Sets the value of the 'retry' field.
   * @param value the value to set.
   */
  public void setRetry(int value) {
    this.retry = value;
  }

  /**
   * Creates a new DocumentKafka RecordBuilder.
   * @return A new DocumentKafka RecordBuilder
   */
  public static io.github.project.openubl.xsender.avro.DocumentKafka.Builder newBuilder() {
    return new io.github.project.openubl.xsender.avro.DocumentKafka.Builder();
  }

  /**
   * Creates a new DocumentKafka RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentKafka RecordBuilder
   */
  public static io.github.project.openubl.xsender.avro.DocumentKafka.Builder newBuilder(io.github.project.openubl.xsender.avro.DocumentKafka.Builder other) {
    if (other == null) {
      return new io.github.project.openubl.xsender.avro.DocumentKafka.Builder();
    } else {
      return new io.github.project.openubl.xsender.avro.DocumentKafka.Builder(other);
    }
  }

  /**
   * Creates a new DocumentKafka RecordBuilder by copying an existing DocumentKafka instance.
   * @param other The existing instance to copy.
   * @return A new DocumentKafka RecordBuilder
   */
  public static io.github.project.openubl.xsender.avro.DocumentKafka.Builder newBuilder(io.github.project.openubl.xsender.avro.DocumentKafka other) {
    if (other == null) {
      return new io.github.project.openubl.xsender.avro.DocumentKafka.Builder();
    } else {
      return new io.github.project.openubl.xsender.avro.DocumentKafka.Builder(other);
    }
  }

  /**
   * RecordBuilder for DocumentKafka instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentKafka>
    implements org.apache.avro.data.RecordBuilder<DocumentKafka> {

    private java.lang.String id;
    private int retry;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.github.project.openubl.xsender.avro.DocumentKafka.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.retry)) {
        this.retry = data().deepCopy(fields()[1].schema(), other.retry);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentKafka instance
     * @param other The existing instance to copy.
     */
    private Builder(io.github.project.openubl.xsender.avro.DocumentKafka other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.retry)) {
        this.retry = data().deepCopy(fields()[1].schema(), other.retry);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.github.project.openubl.xsender.avro.DocumentKafka.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.github.project.openubl.xsender.avro.DocumentKafka.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'retry' field.
      * @return The value.
      */
    public int getRetry() {
      return retry;
    }


    /**
      * Sets the value of the 'retry' field.
      * @param value The value of 'retry'.
      * @return This builder.
      */
    public io.github.project.openubl.xsender.avro.DocumentKafka.Builder setRetry(int value) {
      validate(fields()[1], value);
      this.retry = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'retry' field has been set.
      * @return True if the 'retry' field has been set, false otherwise.
      */
    public boolean hasRetry() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'retry' field.
      * @return This builder.
      */
    public io.github.project.openubl.xsender.avro.DocumentKafka.Builder clearRetry() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentKafka build() {
      try {
        DocumentKafka record = new DocumentKafka();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.retry = fieldSetFlags()[1] ? this.retry : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentKafka>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentKafka>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentKafka>
    READER$ = (org.apache.avro.io.DatumReader<DocumentKafka>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeInt(this.retry);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString();

      this.retry = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString();
          break;

        case 1:
          this.retry = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










