name: Container images generator

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  container-images:
    name: Container Images
    if: ${{ github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn package -DskipTests -Dquarkus.package.type=fast-jar
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: project-openubl/ublhub/ublhub
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: src/main/docker/Dockerfile.fast-jar
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: projectopenubl/ublhub
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: src/main/docker/Dockerfile.fast-jar
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: quay.io
          name: projectopenubl/ublhub
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          dockerfile: src/main/docker/Dockerfile.fast-jar
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
